import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  left,
  right,
}: {
  children: React.ReactNode;
  left: React.ReactNode;
  right: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-2 text-neutral-600">
          <Link href="/tree" className="hover:text-neutral-400 transition">
            Tree
          </Link>
          <Link href="/component" className="hover:text-neutral-400 transition">
            Component
          </Link>
        </nav>

        <div className="flex gap-2 w-full">
          <div className="border w-full flex items-center justify-center">
            {left}
          </div>
          <div className="border w-full flex items-center justify-center">
            {right}
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
